### PR TITLE
Remove destructuring-bind and duplication

### PR DESCRIPTION
**Pull request by charJe**
Should solve #4

### CODE REVIEW

**Comment by charJe** [comment]
@phoe Is this better?

**Comment by phoe** [comment]
Yes, but I think that the `setq result` ignores multiple values that the body can produce. Please verify with something that returns multiple values.

**Comment by charJe** [comment]
Good catch

**Comment by phoe** [comment]
LGTM. I'd personally write some tests for macroexpansions (see https://github.com/phoe/binding-arrows/blob/main/t/test.lisp#L177-L336) but I guess that might be overkill in this case.

**Comment by charJe** [comment]
Obviously the tests here need some improvement (they are just running in `#:cl-user` without test-op). But I see macro expansion tests as a bit much, especially since that could jurastically change in the future as it is in the branch.

**Review by phoe — APPROVED** [review]

**Pull request merged**
